import RightSide from "@/components/RightSide";
import LeftSide from "@/components/LeftSide";
import Navbar from "@/components/Navbar";
import Benner from "@/components/Benner";
import Head from "next/head";
import {motion} from "framer-motion";
import About from "@/components/About";

export default function Home() {
  return (
    <>
      <Head>
        <title>Yusuf Mohammad | My Portfolio</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewpor" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className="w-full h-screen overflow-x-hidden overflow-y-scroll font-bodyFont bg-bodyColor text-textLight">
        <Navbar />
        <div className="w-full h-[88vh] xl:flex items-center gap-20 justify-between">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1.5 }}
            className="fixed left-0 hidden w-20 xl:inline-flex"
          >
            <LeftSide />
          </motion.div>
          <div className="h-[88vh] w-full mx-auto p-4">
            <Benner />
            <About />
            {/* Experience */}
            {/* Projects */}
            {/* Archive */}
            {/* Contact */}
            {/* Footer */}
          </div>
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1.5 }}
            className="fixed bottom-0 hidden w-20 h-full right-6 xl:inline-flex"
          >
            <RightSide />
          </motion.div>
        </div>
      </main>
    </>
  );
};
